### ISSUE TITLE
Windows cursor is unsound:  Unguarded static mut access

### ISSUE THREAD

**Issue by MaulingMonkey** [crossterm-rs/crossterm-cursor#4]
Per https://github.com/rust-lang/rust/issues/53639 , `static mut` is almost always undefined behavior, and the use of it here is no exception.

### Possible fixes
* Replace with atomic vars
* Replace with a Mutex
* Redesign API such that different pieces of code can separately save their own cursor positions independently?

### Unguarded mutate, possibly concurrent with other threads
https://github.com/crossterm-rs/crossterm-cursor/blob/13f6c0878ac871750c5893689e4743ac8084c13b/src/sys/winapi.rs#L113-L115

### Unguarded read, possibly concurrent with other threads mutating
https://github.com/crossterm-rs/crossterm-cursor/blob/13f6c0878ac871750c5893689e4743ac8084c13b/src/sys/winapi.rs#L101-L103

### Definition
https://github.com/crossterm-rs/crossterm-cursor/blob/13f6c0878ac871750c5893689e4743ac8084c13b/src/sys/winapi.rs#L26

**Comment by zrzka** [comment]
Yup. See this PR https://github.com/crossterm-rs/crossterm-cursor/pull/2 where it is fixed with `lazy_static` & `Mutex`. Also check this issue https://github.com/crossterm-rs/crossterm/issues/245.

It's a bit messy (issues here and there) and the reason is that we did separate crates (separate repos) yesterday.

**Comment by MaulingMonkey** [comment]
Ahh fair, I'll close this since it seems to be a duplicate issue then.
